/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 주문 상세 조회
         * @description 사용자의 주문 하나의 상세 정보를 조회한다.<br/>
         *     주문에 포함된 모든 상품을 페이지네이션된 결과로 보여주는 API를 추가로 호출해야 완전한 주문 상세 결과를 얻을 수 있다.
         *
         */
        get: operations["getOrderInfo"];
        /**
         * 주문 수정
         * @description 사용자가 자신이 생성한 주문을 수정한다.
         */
        put: operations["updateOrder"];
        post?: never;
        /**
         * 주문 삭제
         * @description 사용자가 자신이 생성한 주문을 삭제한다.
         */
        delete: operations["cancelOrder"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/orders/{orderUuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 주문 수정
         * @description 특정 유저의 주문을 수정한다.
         */
        put: operations["updateOrder_1"];
        post?: never;
        /**
         * 주문 삭제
         * @description 특정 유저의 주문을 삭제한다.
         */
        delete: operations["deleteOrder"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 주문 리스트 조회
         * @description 사용자의 모든 주문 목록을 조회한다.
         */
        get: operations["getOrders"];
        put?: never;
        /**
         * 주문 생성
         * @description 사용자가 주문을 생성한다.
         */
        post: operations["payment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 상품 목록 조회
         * @description 모든 등록된 상품 목록을 조회한다.
         */
        get: operations["getProductList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 주문 내 상품 단건 조회 (사용자)
         * @description 주문 내에 포함된 상품들을 페이지네이션 해 조회한다.
         */
        get: operations["getProductsInOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 주문 목록 조회
         * @description 모든 유저의 주문을 조회한다.
         */
        get: operations["getAllOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 주문 상세 조회
         * @description 특정 유저의 주문 상세를 조회한다.
         */
        get: operations["getOrderInfo_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/orders/{orderId}/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 주문 내 상품 단건 조회 (관리자)
         * @description 자신이 작성한 주문 내에 포함된 상품들을 페이지네이션 해 조회한다.
         */
        get: operations["getProductsInOrderAdmin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Buyer: {
            email?: string;
        };
        OrderRequestDto: {
            address: string;
            /** Format: int32 */
            zipcode: number;
            items: components["schemas"]["ProductListDto"][];
            buyer: components["schemas"]["Buyer"];
        };
        ProductListDto: {
            productId?: string;
            /** Format: int32 */
            quantity?: number;
        };
        OrderDto: {
            orderId?: string;
            /** Format: date-time */
            orderDate?: string;
            /** Format: int32 */
            totalPrice?: number;
            /** @enum {string} */
            deliveryStatus?: "PENDING" | "SHIPPED" | "DELIVERED" | "CANCELLED";
            buyerEmail?: string;
            address?: string;
            items?: components["schemas"]["ProductItem"][];
        };
        ProductItem: {
            name?: string;
            /** Format: int32 */
            quantity?: number;
        };
        RsDataOrderDto: {
            message?: string;
            data?: components["schemas"]["OrderDto"];
            /** Format: int32 */
            code?: number;
        };
        UserDto: {
            id?: string;
            email?: string;
            /** Format: date-time */
            createdDate?: string;
            /** Format: date-time */
            modifiedDate?: string;
            orders?: components["schemas"]["OrderDto"][];
            buyer?: components["schemas"]["Buyer"];
        };
        RsDataUserDto: {
            message?: string;
            data?: components["schemas"]["UserDto"];
            /** Format: int32 */
            code?: number;
        };
        OrderInfoDto: {
            orderId?: string;
            buyer?: components["schemas"]["Buyer"];
            products?: components["schemas"]["Product"][];
            /** Format: date-time */
            createAt?: string;
            /** Format: date-time */
            modifiedAt?: string;
            /** Format: int32 */
            totalAmount?: number;
            address?: string;
            /** Format: int32 */
            zipcode?: number;
            /** @enum {string} */
            deliveryStatus?: "PENDING" | "SHIPPED" | "DELIVERED" | "CANCELLED";
        };
        Product: {
            productUuid?: string;
            productName?: string;
            category?: string;
            /** Format: int32 */
            productPrice?: number;
            productDescription?: string;
            imageUrl?: string;
        };
        RsDataOrderInfoDto: {
            message?: string;
            data?: components["schemas"]["OrderInfoDto"];
            /** Format: int32 */
            code?: number;
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        PaginationDataProductDto: {
            data?: components["schemas"]["ProductDto"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        ProductDto: {
            productUuid?: string;
            productName?: string;
            category?: string;
            /** Format: int32 */
            productPrice?: number;
            productDescription?: string;
            imageUrl?: string;
        };
        RsDataPaginationDataProductDto: {
            message?: string;
            data?: components["schemas"]["PaginationDataProductDto"];
            /** Format: int32 */
            code?: number;
        };
        OrderListResponse: {
            content?: components["schemas"]["OrderDto"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        RsDataOrderListResponse: {
            message?: string;
            data?: components["schemas"]["OrderListResponse"];
            /** Format: int32 */
            code?: number;
        };
        OrderInfoWithoutItemDto: {
            orderUuid?: string;
            user?: components["schemas"]["UserDto"];
            /** Format: date-time */
            createDate?: string;
            /** Format: date-time */
            modifiedDate?: string;
            /** Format: int32 */
            totalAmount?: number;
            deliveryAddress?: string;
            /** Format: int32 */
            zipCode?: number;
            /** @enum {string} */
            deliveryStatus?: "PENDING" | "SHIPPED" | "DELIVERED" | "CANCELLED";
        };
        RsDataOrderInfoWithoutItemDto: {
            message?: string;
            data?: components["schemas"]["OrderInfoWithoutItemDto"];
            /** Format: int32 */
            code?: number;
        };
        RsDataVoid: {
            message?: string;
            data?: Record<string, never>;
            /** Format: int32 */
            code?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getOrderInfo: {
        parameters: {
            query: {
                email: string;
            };
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RsDataOrderInfoWithoutItemDto"];
                };
            };
        };
    };
    updateOrder: {
        parameters: {
            query: {
                email: string;
            };
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RsDataOrderDto"];
                };
            };
        };
    };
    cancelOrder: {
        parameters: {
            query: {
                email: string;
            };
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    updateOrder_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderUuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RsDataOrderDto"];
                };
            };
        };
    };
    deleteOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    addUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataUserDto"];
                };
            };
        };
    };
    getOrders: {
        parameters: {
            query: {
                email: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RsDataOrderListResponse"];
                };
            };
        };
    };
    payment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RsDataOrderInfoDto"];
                };
            };
        };
    };
    getProductList: {
        parameters: {
            query: {
                "keyword-type"?: string;
                keyword?: string;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataPaginationDataProductDto"];
                };
            };
        };
    };
    getProductsInOrder: {
        parameters: {
            query: {
                email: string;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataPaginationDataProductDto"];
                };
            };
        };
    };
    getAllOrders: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                "max-products"?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RsDataOrderListResponse"];
                };
            };
        };
    };
    getOrderInfo_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RsDataOrderInfoWithoutItemDto"];
                };
            };
        };
    };
    getProductsInOrderAdmin: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataPaginationDataProductDto"];
                };
            };
        };
    };
}
