SET REFERENTIAL_INTEGRITY FALSE;

DROP TABLE if exists `PRODUCT_ORDER_RELATION`;
DROP TABLE if exists `ORDERS`;
DROP TABLE if exists `PRODUCT`;
DROP TABLE if exists `MEMBER`;

SET REFERENTIAL_INTEGRITY TRUE;

CREATE TABLE `MEMBER` (
	`USER_UUID`	VARCHAR(255)	NOT NULL unique primary key,
	`EMAIL`	VARCHAR(255) unique	NULL,
	`CREATE_DATE`	DATETIME	NULL,
	`MODIFIED_DATE`	DATETIME	NULL
);

CREATE TABLE `ORDERS` (
	`ORDER_UUID`	VARCHAR(255) unique	NOT NULL primary key,
	`USER_UUID`	VARCHAR(255)	NOT NULL,
	`CREATE_DATE`	DATETIME	NULL,
	`MODIFIED_DATE`	DATETIME	NULL,
	`TOTAL_AMOUNT`	INTEGER	NULL,
	`DELIVERY_ADDRESS`	VARCHAR(255)	NULL,
	`ZIP_CODE`	INTEGER	NULL,
	`DELIVERY_STATUS`	VARCHAR(255)	NULL,
     foreign key(`USER_UUID`)
     references `MEMBER`(`USER_UUID`)
);


CREATE TABLE `PRODUCT` (
	`PRODUCT_UUID`	VARCHAR(255) unique	NOT NULL,
	`PRODUCT_NAME`	VARCHAR(255)	NULL,
	`CATEGORY`	VARCHAR(255)	NULL,
	`PRODUCT_PRICE`	INTEGER	NULL,
	`PRODUCT_DESCRIPTION`	VARCHAR(255)	NULL,
	`IMAGE_URL`	VARCHAR(255)	NULL
);


CREATE TABLE `PRODUCT_ORDER_RELATION` (
	`PRODUCT_UUID`	VARCHAR(255) 	NOT NULL,
	`ORDER_UUID`	VARCHAR(255) 	NOT NULL,
    foreign key(PRODUCT_UUID)
    references PRODUCT(PRODUCT_UUID),
	foreign key(ORDER_UUID)
    references `ORDERS`(ORDER_UUID)
);